spring.application.name=exercise-tracker-api
spring.datasource.url=${db-url}
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.config.import=optional:./secrets.properties

jwt.durationDays=7

user.defaultPageSize=5

exerciseType.defaultPageSize=5

exercise.defaultPageSize=5

userWorkout.defaultPageSize=5